# Generated by Django 5.0.2 on 2024-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_menus_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='close_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
